version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=ahajiyev628
    ports:
      - '5431:5432'
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db: